services:
  postgres_amx:
    image: postgres
    container_name: postgres_amx
    shm_size: 128mb
    environment:
      POSTGRES_HOST: "${LOCALHOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - db_net
      - db_net_admin
    env_file:
      - .env

  pm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_manager
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: "postgres_amx"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - postgres_amx
    restart: unless-stopped
    networks:
      - db_net
    env_file:
      - .env

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 5454:5454
    networks:
      - db_net_admin

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger_ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api/api.yaml
      BASE_URL: /
    volumes:
      - ./api.yaml:/api/api.yaml:ro
    depends_on:
      - pm

networks:
  db_net:
    driver: bridge
  db_net_admin:
    driver: bridge

volumes:
  postgres_data:
    driver: local
